// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojqwpwxsckyiwnbxbosc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcXdwd3hzY2t5aXduYnhib3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjg3NjMsImV4cCI6MjA2Nzc0NDc2M30.8V_IlOCNQDtIFrx-Sc_r2W4Vcq9u2uJO4PPpo_ueMFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});